### ISSUE TITLE
FasiGit has been reported as a dangerous website.

### ISSUE THREAD

**Issue by zuorong-zhang** [FastGitORG/discussion#10]
![Smartscreen note](https://github.com/zuorong-zhang/zuorong-zhang/raw/main/fastgit_smartscreen.PNG)

**Comment by KevinZonda** [comment]
This is a known problem and we don't know how to fix it.

**Comment by KevinZonda** [comment]
![police i love u](https://user-images.githubusercontent.com/33132228/101984992-e5909080-3c7c-11eb-85bc-c095b2888b08.jpg)
