### ISSUE TITLE
下载 release 中的 apk 文件后被系统认作 zip

### ISSUE THREAD

**Issue by uqsme** [FastGitORG/discussion#11]
安卓手机，使用 [Via](https://coolapk.com/apk/mark.via) 下载贵代理站上的 release apk 后（该浏览器调用系统下载器）系统会用 zip 的打开方式打开，Via 开发者称贵站可能 mimeType 设置有误？

**Comment by KevinZonda** [comment]
我并不认为这是 FastGit 的问题，在打开文件时本身 Android 就会依据文件类型进行匹配（i.e., 并不认为会依赖于MimeType），当然，我们暂且不知Via的工作逻辑。

**Comment by imlk0** [comment]
@TheInterestingSoul 
测试4.1.6版本的via用系统下载器直接输入下面的链接下载apk时能正确调起apk安装器：
https://download.fastgit.org/shadowsocks/shadowsocks-android/releases/download/v5.2.1/shadowsocks--universal-5.2.1.apk

测试的android版本号是android10，手机是一加6
