### ISSUE TITLE
fastgit能否登录github账户？

### ISSUE THREAD

**Issue by tinyvan** [FastGitORG/discussion#15]
RT,
登录不上，且被edge警告不安全
![image](https://user-images.githubusercontent.com/27542299/118383872-773d6900-b634-11eb-8f21-7680c6eaf20d.png)

**Comment by ghost** [comment]
@tinyvan hub.fastgit.org 不能登录 Github 账号

**Comment by KevinZonda** [comment]
对于 edge 的筛查器，我们解决不能。
登录功能不可用。
我们描述其支持在文档中。
感谢你的支持。
