### ISSUE TITLE
Any plan to support github.io?

### ISSUE THREAD

**Issue by AndyZ-Salz** [FastGitORG/discussion#18]
When we use the GitHub Pages, the domain will start as XXX.github.io
Is there any plan to support this domain?

使用Github仓库提供的Pages功能的话，域名是XXX.github.io，是否考虑支持此域名？

**Comment by KevinZonda** [comment]
No.

**Comment by KevinZonda** [comment]
But we might implement it as a commercial project so that we can balance our money which needs support the fastgit runs.

**Comment by AndyZ-Salz** [comment]
good idea! @KevinZonda
