### ISSUE TITLE
how to use git push?

### ISSUE THREAD

**Issue by xiongxin** [FastGitORG/discussion#19]
![2021-09-06_17-19](https://user-images.githubusercontent.com/2803069/132192969-8ba1bc96-8c7a-4109-81fd-0ed245aeddd2.png)

when i want to push commit, i got this.

this is my config list:
```
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
url.https://hub.fastgit.org/.insteadof=https://github.com/
core.editor=vim
init.defaultbranch=main
```

**Comment by KevinZonda** [comment]
should be your GitHub ID and AuthKey
