### ISSUE TITLE
Can you create GitLab and BitBucket mirror?

### ISSUE THREAD

**Issue by zrzjohn** [FastGitORG/discussion#2]
@KevinZonda 
建议添加 GitLab 和 BitBucket 镜像。它们和 GitHub 一样，网速经常不稳定。并且也有很多项目都在这些平台托管。

**Comment by KevinZonda** [comment]
@zrzjohn First of all, thank you for your interest in this project.  At present, our primary task is to maintain the stability of the project.  Recently, we are facing two kinds of pressures: funding and attacks. We are not sure whether it is possible for us to continue operations.

**Comment by zrzjohn** [comment]
> 
> 
> @zrzjohn First of all, thank you for your interest in this project. At present, our primary task is to maintain the stability of the project. Recently, we are facing two kinds of pressures: funding and attacks. We are not sure whether it is possible for us to continue operations.

Someone DDOS FastGit?

**Comment by KevinZonda** [comment]
@zrzjohn Yes, leads to lose approximately 10TiB quotas in 36 hours.

**Comment by zrzjohn** [comment]
@KevinZonda 
What is the relationship between ["FastGit" Mirror Site](https://hub.fastgit.org/) and ["FastGitHub" Tampermonkey Script](https://github.com/RC1844/FastGithub)?

**Comment by KevinZonda** [comment]
@zrzjohn No relationship. Long time ago, I pulled a request to add fastgit support. And, https://greasyfork.org/zh-CN/scripts/402301-fastgit is our official script

**Comment by charliez0** [comment]
@KevinZonda 现在能考虑添加Gitlab镜像吗？攻击和基金问题应该已经解决了

**Comment by zhullyb** [comment]
@charliez0 首先，这不是镜像，而是个反代。
其次，资金问题依然没有解决(能不能撑过2021都是个问题
