### ISSUE TITLE
如何用fastgit登录git

### ISSUE THREAD

**Issue by hdtopku** [FastGitORG/discussion#25]
想要用fastgit登录github，点击登录，就返回错误。请问怎么解决？
![image](https://user-images.githubusercontent.com/14859466/164619229-50f4b8d8-bee4-479c-94c2-23552ab1fe93.png)
![image](https://user-images.githubusercontent.com/14859466/164619395-93e7e40a-22da-4a7f-b1db-5e1bc52ff80d.png)

**Comment by wu-mx** [comment]
文档都不看就来issue瞎bb？

**Comment by hdtopku** [comment]
文档说不支持登录，我知道呢，我也没问你呀，当什么热心群众，懂就把知道的说出来，不懂就别回些没用的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月22日(周五) 晚上7:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FastGitORG/discussion] 如何用fastgit登录git (Issue #25)




 
文档都不看就来issue瞎bb？
