### ISSUE TITLE
accessibility issues

### ISSUE THREAD

**Issue by frankli0324** [FastGitORG/discussion#27]
`raw.fastgit.xyz` unaccessible
observed on May 29

**Comment by KevinZonda** [comment]
xyz or org
If is xyz, it would be correct behaviour

**Comment by frankli0324** [comment]
sorry I meant to say hub.fastgit.xyz

**Comment by KevinZonda** [comment]
> sorry I meant to say hub.fastgit.xyz

hv no idea about it

**Comment by frankli0324** [comment]
seem recovered... I'm in shh and I'm pretty sure I got `connection reset` at noon

**Comment by KevinZonda** [comment]
still quite unstable in the uk

i'll try to investigate why after my final

29 May 2022, 18:45 by ***@***.***:
