### ISSUE TITLE
[Draft] FastGit Download Rebuild

### ISSUE THREAD

**Issue by KevinZonda** [FastGitORG/discussion#3]
Cuz lack of funds, we consider that use another way to provide download service or just stop it.

Here's our possible plans:

1.  Use CDN (e.g., CloudFlare, Akamai) + low-price VM  
**Disadvantage**: may lead low-quality service
1. Shut down  
**Disadvantage**: I don't want to stop it
1. Use another low-price VM to instead now VM  
**Disadvantage**: may lead low-quality service

In any case, we should try to keep the service available as much as possible. And on this basis, try to provide a better experience. At present, the reason why we are struggling with whether we should shut down the service is that we cannot provide the best service.

**Comment by DuckSoft** [comment]
Let's accept donations.

**Comment by KevinZonda** [comment]
> Let's accept donations.

Approved. And I'm ready to release WeChat Shangzan Codes. But, do we have any other better choices?

**Comment by DuckSoft** [comment]
Yes. Let's accept XMR / ZCASH donations.

**Comment by KevinZonda** [comment]
@DuckSoft Maybe I can't keep my wallet very well. (I always lose things.) :( 
Anyway, it's a good idea. But do we have a more convenient way to donate? I mean that people don't need learn much seems too professional knowledge. In the other words, are there any platforms can help users donate? (User provide pay with alipay or wechat pay, and complete transaction automatically)

**Comment by DuckSoft** [comment]
It is convenient. We don't need to teach users how to buy cryptocurrencies. There are already some sorts of ransomware teaching this.

**Comment by Rwing** [comment]
Maybe turning to chinese media or 公众号 is a better option, but it also means more traffic is coming.

**Comment by LionTao** [comment]
> Maybe turning to chinese media or 公众号 is a better option, but it also means more traffic is coming.

I agree,  turning to wechat public accounts can attract a lot of people.
But "a lot of people" not always means good, I think there are two major concerns about using Wechat public accounts:
1. Due to the large audience attracted, we need proper donation channels.
2. We need to find a way to properly decouple with Wechat payment system to protect privacy for both fastgit official and our users. May be something like a pyment platform can solve the problem(e.g. HantePay)?

I think donation is key for fastgit to continuously provide service.
But considering how github itself was blocked, I think we should set some limitation for public content or using premium feature to filter(or limit) those "Malicious" content. 
I don't want fasgit to be blocked like github.

Anyway fastgit helps me a lot, thank you!:smiley:

**Comment by KevinZonda** [comment]
@LionTao I don't think zanshang code may lead to privacy breaches. My concern is primarily with 公众号 and Alipay QR code.

The actual sustainability of donations is a volatile indicator. But it can help us anyway. The best solution to us is to find an IDC that is willing to sponsor us.

Btw, as all we know, we are incapable of fighting IDS. The only thing we can do is pray.

**Comment by KevinZonda** [comment]
Thanks for @TingyiChen's help, DL works fine in China Unicom.

**Comment by favoyang** [comment]
Perhaps another option on the table is turning the download endpoint to a web page based service. So you can inject ads during the process, and returns the user a short term signed URL to download assets. The currently unsigned download service will be discontinued. Not awesome as it is now, but for surviving.

A quota-based premium plan is also here. Each premium user can get a dedicated domain for acceleration. But consider the cost to build a SaaS system. It may be just cost too much energy and risky to find a market.

Overall the first option is easier to build and verify (the biz perspective).

**Comment by KevinZonda** [comment]
@favoyang Thanks for your advice!
I don't really expect users levels or such things. It seems like a form of evil. But for enterprises I think we can try to  negotiate (although i don't think that we have such customers now).
And the download ADs I'm still hesitant about it. Google adsense seems to be really hard to apply by FastGit...

**Comment by favoyang** [comment]
Sure, you can always postpone the decision until the happy-pain point - growth.

**Comment by KevinZonda** [comment]
No need. Thanks 365Node!
