### ISSUE TITLE
Need a .net global tool to do git operation with fastgit ?

### ISSUE THREAD

**Issue by Rwing** [FastGitORG/discussion#5]
FYI https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools
I can help develop it if you want.

**Comment by KevinZonda** [comment]
you can help develop it, and donate your repository to us if you want :D

**Comment by KevinZonda** [comment]
@KevinZonda And I'm willing to help it if you need, lol

**Comment by Rwing** [comment]
The package id 'fgit' is already taken on nuget, I'm in communication with the owner to transfer it to me. 😭

**Comment by Rwing** [comment]
Thanks to @msfcolombo.
I've already upload package to nuget, https://www.nuget.org/packages/fgit
So I can donate the project to you, but I dont know how to do it, can you tell me?

**Comment by KevinZonda** [comment]
@Rwing i'll invite you into organization

**Comment by KevinZonda** [comment]
@Rwing Check your email plz, :)

**Comment by Rwing** [comment]
done. :)
