### ISSUE TITLE
Can you add a space between "↓ Code" and "↓ FastGit" ?

### ISSUE THREAD

**Issue by zrzjohn** [FastGitORG/discussion#7]
![Add a Space](https://preview.yozodcs.com/fcscloud/view/preview/K1X1x_bU6J-gTDPCo7PIz1PCPwOg24gtQPJRZ7Ajaj6Zc2G4sfVUTwnOcTmO97vPeqTM3aH0U5UmHY20HosAaPzpLlwFbRvbJ9H1ffZGr2j78p0nLuYgol4LwjqW4qHQZhbgDFs8Vi0tYKApUZFO3pMMYe2_li-HzQJce-OojbswXg3tcjeaMxYC15IEmDuTiYGVjo8XIjygTvKFh6YawOUDq2QedRoSEeMeBOWpjCXToWQovdnZ_tL5RiGBNc4ALdIpSM5vaxCQGEz7d6261eKkA_opTK2YU6yVsUevHDYF_C9rLoJY3I4sp70WxBPDcuHLvSG3UzxcON1l8ytc9Q==/add-a-space.files/file0001.PNG)

**Comment by KevinZonda** [comment]
Hello! Thanks for joining discussion. But seems your picture is broken, I tried to visit your picture link, and it said `{"data":"","message":"非法请求","errorcode":35}`.

**Comment by KevinZonda** [comment]
According to long-time no reply, this issue will be closed. If you still have questions, feel free to contact with us.
